apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: c975e2gq4-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-89d6e34afe.pysq.p3.openshiftapps.com/rhtap/rhtap-qe:8b20b0353457ff2c857dea5c2fe7631412f6a629@sha256:b5f1e70e0f00233f9e30d7c20d67249ea4e931fb920d2b0e1d6f208e9733bd20
        name: container-image  
